#!/bin/bash
XDEV_PATH="${HOME}/Documents/xdev"
cd "$XDEV_PATH" || exit
git pull

xset r rate 170 60
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# bash "${XDEV_PATH}/bin/hv-os-image-init.sh"
# bash ev-idle-mouse.sh

# color
#xrandr --output HDMI-0 --gamma 1:0.7:0.6 --brightness 0.87
redshift -v -P -O 5600 -g 0.8 -b 0.9  -m randr